#!/bin/bash -u -e

function clear_tmp_folders()
{
    rm -rf tmp_classes_in
    rm -rf tmp_classes_out
}

# Helper function to unpack, trim, and repack a jar
# arg1: jar name, to be found in "$SOURCE_JDK"/jre/lib/
function process_jar
{
    local JAR_NAME=$1

    echo "Unzipping $JAR_NAME"

    # Remove temp directories
    clear_tmp_folders
    mkdir tmp_classes_in

    # Unzip the jar
    unzip -d tmp_classes_in "$SOURCE_JDK"/jre/lib/$JAR_NAME 1>/dev/null

    echo "Repacking $JAR_NAME"

    # Rsync the files we want to keep into tmp_classes_out/
    rsync --delete --delete-excluded --dirs --prune-empty-dirs --archive --filter="merge classes.filter" tmp_classes_in/ tmp_classes_out/

    # Re-create the jar
    jar -cf "$DEST"/jre/lib/$JAR_NAME -C tmp_classes_out .
}

#############
# Main script
#############

if [ $# -ne 3 ]; then
    echo "usage: $0 [osx|win] [source jdk] [destination folder]"
    echo "example: $0 win openjdk-1.7.0 openjdk-1.7.0-trimmed"
    exit 1
fi

OS="$1"
SOURCE_JDK="$2"
DEST="$3"

if [ $OS != "win" ] && [ $OS != "osx" ]; then
    echo "Error: first parameter must be 'osx' or 'win'"
    exit 1
fi

echo "Copying files..."
rsync --delete --delete-excluded --dirs --prune-empty-dirs --archive --filter="merge $OS/files.filter" "$SOURCE_JDK"/ "$DEST"/

process_jar charsets.jar
process_jar jce.jar
process_jar jsse.jar
process_jar resources.jar
process_jar rt.jar

clear_tmp_folders
